services:
  sql-db:
    image: mariadb:latest
    restart: always
    volumes:
      - $PWD/project/sql-db/conf.d/:/etc/mysql/conf.d
      - $PWD/project/sql-db/repo/mysql/:/var/lib/mysql
    ports:
      - "3306:3306"
